services:
  postgres-db:
    image: postgres
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todo_user -d todo_db"]
      interval: 10s
      timeout: 5s

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DATABASE: postgres
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      postgres-db:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s

volumes:
  postgres-data: